# Generated by Django 4.1.7 on 2023-02-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radio',
            old_name='streem_url',
            new_name='stream_url',
        ),
    ]
