# Generated by Django 4.1.7 on 2023-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_rename_streem_url_radio_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='radio',
            name='categories',
            field=models.ManyToManyField(blank=True, to='radio.category', verbose_name='Radio Categories'),
        ),
    ]
