# Generated by Django 4.1.7 on 2023-02-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_category_radio_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='radio',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='radios', to='radio.category', verbose_name='Radio Categories'),
        ),
    ]
